### ISSUE TITLE
代码注释问题

### ISSUE THREAD

**Issue by jikeyoung** [youyuge34/Poems_generator_Keras#1]
楼主厉害了!!!
看了很多关于机器写诗的，大多都是基于TF的，模型搭建实在搞得脑袋一团麻，
楼主你这个很简单明了，哈哈哈，请问能再详细给点注释或类似思维导图那种结构图吗，
机器学习新手入坑，有些地方还是看的不大明白。。。

**Comment by youyuge34** [comment]
@jikeyoung 
不懂的地方直接issues里直接问就行了~~
